#!/usr/bin/env python3
"""Generate config/workflow-owners.yaml: one row per workflow, owner blank.

Suggestions are evidence-cited and ALWAYS confirmed: false. The pipeline must
ignore any row whose confirmed flag is not true. See README, "Workflow owners".
"""
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
INVENTORY = ROOT / "00-master" / "Team_Task___Workflow_Inventory"
OUT = ROOT / "config" / "workflow-owners.yaml"

# Theme-level suggestions. Each entry: (canonical person, evidence string).
# Evidence is a literal cell/row a human can re-open and check. Nothing here is
# asserted; every one lands in the file as confirmed: false.
THEME_SUGGESTION = {
    2:  ("Adil Panwar",      "IAims!Q1 2026 'Hiring/Training SMEs/TAs from the US and India'"),
    4:  ("Adil Panwar",      "IAims 'Curriculum Development - New' / 'Revamping existing Courses/Curriculum'"),
    11: ("Utkarsh Raj",      "IAims!Q1 2026 r13 'New Curriculum Development For B2B'"),
    12: ("Uday Mehtani",     "Domains_Courses Owners!Sheet1 r23-r25 Masterclass primary owner 'Uday'"),
    15: ("M Prasad Khuntia", "IAims!Q1 2026 r5-r8 'Ratings (Old B2C Courses)' / 'NPS (Old B2B/B2C Courses)'"),
}
# Workflow-level suggestions override the theme default.
WORKFLOW_SUGGESTION = {
    "8.3": ("Adil Panwar",      "IAims 'IP Refunds' / 'Refunds/Retention'; workflow 8.3 is Refund Analysis"),
    "2.2": ("Karthika S",       "SME_Interview_Demo Audit Rubrics!SME_Interview 'Interviewer Name' = Karthika"),
}


def parse(text):
    theme, rows = None, []
    for ln in text.split("\n"):
        m = re.match(r"^##\s+(\d+)\.\s+(.+?)\s*$", ln)
        if m:
            theme = (int(m.group(1)), m.group(2).strip())
            continue
        m = re.match(r"^###\s+(\d+)\.(\d+)\s+(.+?)\s*$", ln)
        if m and theme:
            rows.append({
                "id": f"{m.group(1)}.{m.group(2)}",
                "name": m.group(3).strip(),
                "theme_id": theme[0],
                "theme": theme[1],
            })
    return rows


def q(s):
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def main():
    rows = parse(INVENTORY.read_text(encoding="utf-8"))
    if len(rows) != 92:
        sys.exit(f"expected 92 workflows, parsed {len(rows)} — inventory changed, review before regenerating")

    out = [
        "# workflow-owners.yaml — workflow-level ownership, filled in by hand.",
        "#",
        "# No file in the corpus assigns an owner to a workflow (risk R2). This file is",
        "# the only source for the Workflow -> Person edge, which is the sole bridge",
        "# between graph component A (Theme/Workflow) and component B (Domain/Person/",
        "# Program/Module/Instructor). Without it the graph ships as two disconnected",
        "# halves.",
        "#",
        "# HOW TO FILL: put a canonical name from people.yaml in `owner`. One name.",
        "# Use `secondary` for a backup. Leave `owner` empty if genuinely unowned —",
        "# empty is a valid, meaningful answer and is preserved as 'no owner'.",
        "#",
        "# `suggestion` is a GUESS from adjacent evidence, never an assertion. The",
        "# pipeline ignores it. To accept one, copy the name into `owner` yourself.",
        "# Rows are emitted with confirmed: false; the pipeline skips every row where",
        "# confirmed is not true, so a half-filled file is safe to build from.",
        "#",
        f"# Generated by pipeline/gen_workflow_owners.py from {INVENTORY.name}",
        f"# {len(rows)} workflows across 16 themes. Do not hand-edit ids, names or themes —",
        "# re-run the generator; it preserves nothing, so fill owners in a copy first.",
        "",
        "version: 1",
        "workflows:",
    ]

    current_theme = None
    for r in rows:
        if r["theme_id"] != current_theme:
            current_theme = r["theme_id"]
            out.append("")
            out.append(f"  # ---- {current_theme}. {r['theme']} ----")
        sug = WORKFLOW_SUGGESTION.get(r["id"]) or THEME_SUGGESTION.get(r["theme_id"])
        out.append(f"  - id: {q(r['id'])}")
        out.append(f"    name: {q(r['name'])}")
        out.append(f"    theme_id: {r['theme_id']}")
        out.append(f"    theme: {q(r['theme'])}")
        out.append("    owner: ")
        out.append("    secondary: ")
        out.append("    confirmed: false")
        if sug:
            out.append(f"    suggestion: {q(sug[0])}")
            out.append(f"    suggestion_evidence: {q(sug[1])}")

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(out) + "\n", encoding="utf-8")
    n_sug = sum(1 for r in rows if WORKFLOW_SUGGESTION.get(r["id"]) or THEME_SUGGESTION.get(r["theme_id"]))
    print(f"wrote {OUT.relative_to(ROOT)}: {len(rows)} rows, {n_sug} carry a suggestion, 0 owners set")


if __name__ == "__main__":
    main()
