#!/usr/bin/env python3
"""Generate knowledge/INDEX.md from graph.json. NEVER hand-write counts here.

The reference implementation hand-wrote 1,072 files / 61 clients / 773
instructors into plugin.json and its website while the actual graph held
1,833 / 32 / 351 — roughly 70% wrong, published, and nobody caught it. Their
auto-generated INDEX.md stayed correct. That is the whole argument for this file.
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from pipeline.lib import graphio, taxonomy                             # noqa: E402
from pipeline.lib.paths import KNOWLEDGE_DIR, REPO_ROOT                # noqa: E402

README = REPO_ROOT / "README.md"
PLUGIN = REPO_ROOT / ".claude-plugin" / "plugin.json"
OPEN_MARK, CLOSE_MARK = "<!-- generated:counts -->", "<!-- /generated:counts -->"

DEFERRAL = """> ## Built from Google Drive, via a service account
>
> `pipeline/00_fetch_drive.py` is live. The cache is fetched read-only from the
> configured folder and pass 1 reads it from disk.
>
> **The three-tab "NP Autopilot" master spreadsheet is NOT in that folder.**
> Established by listing all 374 worksheets across 18 workbooks and searching for
> `Automations`, `All Tasks` and `To-Do & Working Notes` — no match, and none for
> a fuzzy search either. So `Owner` and `Automation` are not imminent node types.
>
> That is a statement about **this folder**, which is the corpus scope we have
> defined. It is not a statement about all of Drive.
>
> The counts below remain FLOORS: 127 of 374 worksheets have been read by an
> entity scan. Fetching the corpus from Drive fixed reproducibility, not
> coverage."""


def readme_block(meta: dict, version: str) -> str:
    """The counts README publishes, rendered from graph.json and plugin.json.

    README used to hand-write these. The counts were right; the version was two
    bumps stale (`v0.1.2` against a 0.1.4 manifest), and the node table omitted
    `file` entirely, so it summed to 4,974 against a stated 5,048 — the same
    defect as AUDIT 6.1, in prose.
    """
    nodes = meta["node_counts"]
    edges = meta["edge_counts"]
    w = meta.get("withheld") or {}
    lines = [
        f"`{meta['nodes']:,} nodes · {meta['edges']:,} edges` at plugin "
        f"**v{version}**, built `{meta['built_at'][:10]}`.",
        "",
    ]
    if w.get("nodes"):
        lines += [
            f"**Plus {w['nodes']:,} nodes and {w['edges']:,} edges withheld from "
            f"this repo** — `sensitive: true`, hiring rejections and in-pipeline "
            f"candidates about named external people. They live in "
            f"`{w['file']}`, which is gitignored, and are projected behind the "
            f"`recruiting` access policy. Full graph is "
            f"{meta['nodes'] + w['nodes']:,} nodes / "
            f"{meta['edges'] + w['edges']:,} edges. See `docs/DECISIONS.md` §F.2.",
            "",
        ]
    lines += ["| node type | count |", "|---|---:|"]
    lines += [f"| {t} | {n:,} |" for t, n in sorted(nodes.items(), key=lambda kv: -kv[1])]
    lines += ["", "| edge type | count |", "|---|---:|"]
    lines += [f"| {t} | {n:,} |" for t, n in sorted(edges.items(), key=lambda kv: -kv[1])]
    zero = [t for t in taxonomy.edge_type_names() if edges.get(t, 0) == 0]
    if zero:
        lines += ["", "Declared but at zero, deliberately: "
                  + ", ".join(f"`{t}`" for t in zero) + ". No evidence in the corpus."]
    return "\n".join(lines)


def write_readme(meta: dict) -> bool:
    """Splice the generated block into README.md. Returns True if it changed."""
    if not README.exists():
        return False
    text = README.read_text(encoding="utf-8")
    if OPEN_MARK not in text or CLOSE_MARK not in text:
        print(f"  README.md has no {OPEN_MARK} block — skipped")
        return False
    version = json.loads(PLUGIN.read_text(encoding="utf-8"))["version"]
    head, rest = text.split(OPEN_MARK, 1)
    _, tail = rest.split(CLOSE_MARK, 1)
    new = f"{head}{OPEN_MARK}\n{readme_block(meta, version)}\n{CLOSE_MARK}{tail}"
    if new == text:
        return False
    README.write_text(new, encoding="utf-8")
    return True


def main() -> int:
    # The PUBLIC file only. INDEX.md and README ship to collaborators who hold
    # nothing else, so reporting the union would describe a graph they do not
    # have. meta.withheld names the difference explicitly instead.
    g = json.loads((KNOWLEDGE_DIR / "graph.json").read_text(encoding="utf-8"))
    meta = g["meta"]
    lines = [
        "# INDEX",
        "",
        "**Auto-generated by `pipeline/gen_index.py`. Do not hand-edit — every",
        "count here comes from `graph.json`.**",
        "",
        DEFERRAL,
        "",
        f"- Built: `{meta['built_at']}`",
        f"- Taxonomy version: `{meta['taxonomy_version']}`",
        f"- Source: `{meta['source']}`",
        "",
        "## Nodes",
        "",
        "| type | count | expect |",
        "|---|---|---|",
    ]
    for t in taxonomy.node_type_names():
        n = meta["node_counts"].get(t, 0)
        exp = taxonomy.expected_count(t)
        lines.append(f"| `{t}` | {n} | {'—  (floor; coverage incomplete)' if exp is None else exp} |")
    lines += [f"| **total** | **{meta['nodes']}** | |", "", "## Edges", "",
              "| type | count |", "|---|---|"]
    for e in taxonomy.edge_type_names():
        lines.append(f"| `{e}` | {meta['edge_counts'].get(e, 0)} |")
    lines += [f"| **total** | **{meta['edges']}** |", "",
              "## Coverage caveat", "",
              "`person`, `instructor` and `module` have no expected count. 25 of the 75",
              "corpus files went unread by any entity scan until this build; the figures",
              "above are floors, not totals. Never quote one as a total.", ""]
    (KNOWLEDGE_DIR / "INDEX.md").write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote INDEX.md — {meta['nodes']} nodes, {meta['edges']} edges")
    if write_readme(meta):
        print("wrote README.md counts block")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
