#!/usr/bin/env python3
"""Generate public/stats.json for the landing page. NEVER hand-write these.

The reference implementation hand-wrote counts into plugin.json and its website
while the real graph held roughly 30% of what it claimed — published, and nobody
caught it. `gen_index.py` exists for that reason and this file is the same
argument applied to the one surface where a stale number is least likely to be
noticed: the page everybody sees and nobody re-reads.

IT READS THE PROJECTION, NOT graph.json, AND THAT IS DELIBERATE. There are two
graphs in this project and confusing them has already produced three wrong
figures (STATE.md §1). `knowledge/graph.json` is the PIPELINE graph — 5,048
nodes, provenance and sensitive rows included — and it is not what the explorer
serves. `projection_meta` is the row the projection writes about itself, so a
landing page built from it cannot describe a graph the visitor is not looking at.

Everything here is derivable. Nothing is asserted: the worksheet-coverage caveat
is stated in words on the page rather than as a number, because 127-of-374 is
not derivable from the projection and a hand-typed number in a generated file is
the exact thing this script exists to prevent.
"""
from __future__ import annotations

import json
import os
import sys
from datetime import datetime, timezone
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from pipeline.lib import db                                            # noqa: E402
from pipeline.lib.paths import REPO_ROOT                               # noqa: E402

#: Redirectable, for the same reason NP_BUILD_LOG is. `project_graph.py` calls
#: this on every successful public projection, and the test suite RE-PROJECTS
#: against the real database — so without an override a test run would rewrite
#: a tracked file in the working tree. That is the exact fault
#: tests/test_build_log_isolation.py exists to prevent, and this file
#: reintroduced it the day it was written.
OUT = Path(os.environ.get("NP_LANDING_STATS")
           or REPO_ROOT / "public" / "stats.json")


def collect(conn) -> dict:
    with conn.cursor() as cur:
        cur.execute("""
            select node_count, edge_count, source_count, built_as_of,
                   projected_at, scope
            from projection_meta where scope = 'public'
            order by projected_at desc limit 1
        """)
        row = cur.fetchone()
        if row is None:
            raise SystemExit("no projection_meta row for scope 'public' — the "
                             "graph has not been projected, so there is nothing "
                             "honest to put on the landing page")
        nodes, edges, sources, as_of, projected_at, scope = row

        cur.execute("select type, count(*) from nodes group by type order by 2 desc")
        by_type = {t: c for t, c in cur.fetchall()}

        cur.execute("select count(distinct file) from node_sources where file is not null")
        files = cur.fetchone()[0]

    return {
        "_comment": ("GENERATED by pipeline/gen_landing_stats.py from the "
                     "PROJECTION (not knowledge/graph.json). Do not edit: "
                     "tests/test_landing_stats.py fails on drift."),
        "scope": scope,
        "nodes": nodes,
        "edges": edges,
        "provenance_records": sources,
        "files": files,
        "by_type": by_type,
        "built_as_of": str(as_of),
        "projected_at": projected_at.astimezone(timezone.utc)
                        .strftime("%Y-%m-%dT%H:%M:%SZ"),
    }


def main() -> int:
    with db.connect(db.SESSION) as conn:
        stats = collect(conn)
    payload = json.dumps(stats, indent=2, sort_keys=True) + "\n"
    changed = (not OUT.exists()) or OUT.read_text(encoding="utf-8") != payload
    OUT.write_text(payload, encoding="utf-8")
    print(f"{'wrote' if changed else 'unchanged'} {OUT.relative_to(REPO_ROOT)}"
          f"  {stats['nodes']} nodes / {stats['edges']} edges"
          f"  projected {stats['projected_at']}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
