#!/usr/bin/env python3
"""Generate knowledge/INDEX.md from graph.json. NEVER hand-write counts here.

The reference implementation hand-wrote 1,072 files / 61 clients / 773
instructors into plugin.json and its website while the actual graph held
1,833 / 32 / 351 — roughly 70% wrong, published, and nobody caught it. Their
auto-generated INDEX.md stayed correct. That is the whole argument for this file.
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from pipeline.lib import taxonomy                                      # noqa: E402
from pipeline.lib.paths import KNOWLEDGE_DIR                           # noqa: E402

DEFERRAL = """> ## ⚠ This graph was NOT built from Google Drive
>
> It is built from a **hand-exported local folder**. `pipeline/00_fetch_drive.py`
> exists and has **never been run**. Drive ingestion is **deferred to v2**, not
> cancelled.
>
> **The three-tab "NP Autopilot" master spreadsheet has never been located.** It
> is the file the original brief's taxonomy was derived from. If it exists in
> Drive, then:
>
> - `Owner` and `Automation` may return as node types, and
> - doc 05 (the taxonomy proposal) is redone.
>
> Until pass 0 runs, every count below is over what one person happened to
> export by hand, and no statement about what Drive contains is supported."""


def main() -> int:
    g = json.loads((KNOWLEDGE_DIR / "graph.json").read_text(encoding="utf-8"))
    meta = g["meta"]
    lines = [
        "# INDEX",
        "",
        "**Auto-generated by `pipeline/gen_index.py`. Do not hand-edit — every",
        "count here comes from `graph.json`.**",
        "",
        DEFERRAL,
        "",
        f"- Built: `{meta['built_at']}`",
        f"- Taxonomy version: `{meta['taxonomy_version']}`",
        f"- Source: `{meta['source']}`",
        "",
        "## Nodes",
        "",
        "| type | count | expect |",
        "|---|---|---|",
    ]
    for t in taxonomy.node_type_names():
        n = meta["node_counts"].get(t, 0)
        exp = taxonomy.expected_count(t)
        lines.append(f"| `{t}` | {n} | {'—  (floor; coverage incomplete)' if exp is None else exp} |")
    lines += [f"| **total** | **{meta['nodes']}** | |", "", "## Edges", "",
              "| type | count |", "|---|---|"]
    for e in taxonomy.edge_type_names():
        lines.append(f"| `{e}` | {meta['edge_counts'].get(e, 0)} |")
    lines += [f"| **total** | **{meta['edges']}** |", "",
              "## Coverage caveat", "",
              "`person`, `instructor` and `module` have no expected count. 25 of the 75",
              "corpus files went unread by any entity scan until this build; the figures",
              "above are floors, not totals. Never quote one as a total.", ""]
    (KNOWLEDGE_DIR / "INDEX.md").write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote INDEX.md — {meta['nodes']} nodes, {meta['edges']} edges")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
